{
    "code": 0,
    "is_server_open": true,
    "is_firewall_open": false,
    "need_track_hotupdate": true,
    "min_hint_size": 1,
    "billboard_cdn_url": "https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/idolzjifnmi101.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/idolzjifnmi102.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/idolzjifnmi103.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/idolzjifnmi104.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/idolzjifnmi105.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/idolzjifnmi106.ff_extend;https://dl.dir.freefiremobile.com/common/OB54/CSH/patchupdate/idolzjifnmi107.ff_extend",
    "billboard_msg": "[FFF000]Server Ku Matiin Dulu, Sedang Maintenance Silahkan Ke Saluran Untuk Mendapatkan Info Terbaru",
    "patchnote_url": "https://dl.dir.freefiremobile.com/common/web_event/aswqooiwd/eCYh86t5.html?lang=ind",
    "web_url": "",
    "billboard_bg_url": "https://files.catbox.moe/y4z6hm.jpg",
    "max_store": "",
    "max_web": "",
    "max_video": "",
    "remote_version": "1.130.22",
    "remote_option_version": "optionallocres:50|optionalavatarres:791|optionalclothres:1228|optionalfootballres:27|optionalfullscreencgres:319|optionalhuntinggroundres:246|optionalinfection:125|optionalingameres:503|optionallobbyres:640|optionallonewolfres:86|optionallonewolfstrikeoutres:59|optionalludores:42|optionalmap1res:385|optionalmap2res:156|optionalmap4res:139|optionalmaphippores:118|optionalmapres:357|optionalnewblast:163|optionalpetres:910|optionalrushb:108|optionalrushingpetsres:84|optionalsnowduelres:65|optionalsocialres:223|optionaltrainingres:297|optionalugcres:844|optionalvoiceres:344|optionalwerewolves:153|optionalwerunres:92|optionalmapponyres:204|optionalugcoldparadiseres:34|optionalmultiregionres:29",
    "remote_option_version_astc": "optionallocres:50|optionalavatarres:753|optionalclothres:1228|optionalfootballres:29|optionalfullscreencgres:306|optionalhuntinggroundres:216|optionalinfection:124|optionalingameres:461|optionallobbyres:640|optionallonewolfres:206|optionallonewolfstrikeoutres:155|optionalludores:175|optionalmap1res:385|optionalmap2res:192|optionalmap4res:175|optionalmaphippores:120|optionalmapres:391|optionalnewblast:162|optionalpetres:910|optionalrushb:241|optionalrushingpetsres:217|optionalsnowduelres:65|optionalsocialres:215|optionaltrainingres:267|optionalugcres:786|optionalvoiceres:379|optionalwerewolves:286|optionalwerunres:81|optionalmapponyres:204|optionalugcoldparadiseres:33|optionalmultiregionres:27",
    "cdn_url": "https://dl.gmc.freefiremobile.com/live/ABHotUpdates/",
    "abhotupdate_cdn_url": "/freefireth/live/ABHotUpdates/",
    "backup_cdn_url": "https://dl.gmc.freefiremobile.com/live/ABHotUpdates/",
    "server_url": "https://loginbp.ggpolarbear.com/",
    "is_review_server": false,
    "appstore_url": "http://play.google.com/store/apps/details?id=com.dts.freefireth",
    "backup_appstore_url": "",
    "force_to_restart_app": false,
    "country_code": "BR",
    "gdpr_version": 0,
    "client_ip": "2001:448a:7030:326:bad:d6a3:994f:ffb2",
    "maintenance_announcement": null,
    "maintenance_region": null,
    "need_check_ip_list": [
        "202.81.108.9"
    ],
    "network_log_server": "https://idnetwork.ggblueshark.com/",
    "web_log_server": "https://networkselftest.ff.garena.com/api/",
    "login_failed_count": 2,
    "test_url": "",
    "img_cdn_url": "https://dl.gmc.freefiremobile.com/common/",
    "core_url": "csoversea.castle.freefiremobile.com",
    "core_ip_list": [
        "0.0.0.0",
        "50.109.27.134",
        "129.226.2.163",
        "129.226.1.13",
        "129.226.1.16"
    ],
    "is_update_btn_show": false,
    "is_use_multi_download": true,
    "use_login_optional_download": true,
    "use_background_download": false,
    "use_background_download_lobby": false,
    "use_backgound_download_mem_thredshold": 2.79999995231628,
    "garena_login": false,
    "garena_hint": false,
    "enable_clear_mem_when_autopause": true,
    "space_required_in_GB": 1.48,
    "gop_url": "",
    "login_download_optionalpack": "optionalclothres:shaders|optionalpetres:optionalpetres_commonab_shader|optionallobbyres:",
    "gamevar": "var_name,comment,var_type,var_value,var_region,var_platform\nEnableVariableFFVoiceIDC,EnableVariableFFVoiceIDC,bool,false,,\nEnableYieldMutexDuringAsyncLoad,EnableYieldMutexDuringAsyncLoad,bool,false,,\nNinthProgressLoadingDuration,NinthProgressLoadingDuration,float,0,,\nEnableUGCScrollViewCulling,EnableUGCScrollViewCulling,bool,false,,\nEnableUGCScrollViewCulling,EnableUGCScrollViewCulling,bool,false,,\nReservedInt01,ReservedInt01,int,5,,\nNinthLevelPortalRadius,NinthLevelPortalRadius,float,20,,\nEnable2018ABstreamed,Enable2018ABstreamed,bool,false,,ios\nEnableAsyncCullResultsRelease,EnableAsyncCullResultsRelease,bool,false,,ios\nReservedInt02,ReservedInt02,int,30,,\nEnableUGCHalfwayJoin,EnableUGCHalfwayJoin,bool,false,,\nLadderMatchSplashRegionOn,LadderMatchSplashRegionOn,string,PK;EUROPE;TH;SG;TW;BR,,\nSensitivityMaxSetting,SensitivityMaxSetting,float,9.0,,\nSensitivity1PMaxSetting,Sensitivity1PMaxSetting,float,9.0,,\nX1ScopeMaxSetting,X1ScopeMaxSetting,float,9.0,,\nX2ScopeMaxSetting,X2ScopeMaxSetting,float,9.0,,\nX4ScopeMaxSetting,X4ScopeMaxSetting,float,9.0,,\nX8ScopeMaxSetting,X8ScopeMaxSetting,float,9.0,,\nFreeLookMaxSetting,FreeLookMaxSetting,float,9.0,,\nNoResetUplayerAnimationWhenReloading,NoResetUplayerAnimationWhenReloading,bool,False,,\nKeepFallingLandAnim,KeepFallingLandAnim,bool,False,,\nCallStopEmoteAtPlayFireAnim,CallStopEmoteAtPlayFireAnim,bool,True,,\nBanFastRunWhenFire,BanFastRunWhenFire,bool,True,,\nFixCrouchFireAnim,FixCrouchFireAnim,bool,True,,\nEnableIceWallHacker,EnableIceWallHacker,bool,False,,\nEnableIceWallHackerKill,EnableIceWallHackerKill,bool,False,,\nEnableHipHackerKill,EnableHipHackerKill,bool,False,,\nEnableSendHackStoreLog,EnableSendHackStoreLog,bool,False,,\nCameraHackRuntimeCheckIsWaitingCabinPhase,CameraHackRuntimeCheckIsWaitingCabinPhase,bool,False,,\nDisableErrorLog,DisableErrorLog,bool,True,,\nEnableCheckSandModeBySwitchFunc,EnableCheckSandModeBySwitchFunc,bool,False,,\nCleanFFAntiState,CleanFFAntiState,bool,True,,\nSaveLocationInPlatform,SaveLocationInPlatform,bool,False,,\nEnableGGPDecryptFailureProtection,EnableGGPDecryptFailureProtection,bool,False,,\nEnableFileInfoEncryptionAndroid,EnableFileInfoEncryptionAndroid,bool,False,,\nEnableFileInfoEncryptionIOS,EnableFileInfoEncryptionIOS,bool,False,,\nOptionalDeepFileCheck,OptionalDeepFileCheck,bool,False,,\nEnableOBBCheck,EnableOBBCheck,bool,False,,\nModifyAvatarCode,ModifyAvatarCode,bool,True,,\nModifyAvatarDataCode,ModifyAvatarDataCode,bool,True,,\nNeedSignatureInfo,NeedSignatureInfo,bool,True,,\nEnableFirebase_Crashlytics,EnableFirebase_Crashlytics,bool,False,,\nFFAntihackDisabledRegions,FFAntihackDisabledRegions,string,US,CN,TW,TH,VN,ID,PT,ES,RU,KR,FR,DE,TR,IN,JP,RO,SA,MM,PK,BD,MY,,\nFFAntihackDisabledClientVariant,FFAntihackDisabledClientVariant,string,ClientUsingVersion_NONE,ClientUsingVersion_NORMAL,ClientUsingVersion_MAX,ClientUsingVersion_FFI,ClientUsingVersion_MAX_HPE,ClientUsingVersion_FFVN,,\nEnableMtpLiteDataRegion,EnableMtpLiteDataRegion,string,,,\nFFAntihackEmulatorCheckDisbaledClientVariant,FFAntihackEmulatorCheckDisbaledClientVariant,string,ClientUsingVersion_NONE,ClientUsingVersion_NORMAL,ClientUsingVersion_MAX,ClientUsingVersion_FFI,ClientUsingVersion_MAX_HPE,ClientUsingVersion_FFVN,,\nForceTutorial_ChangeHudABTest,ForceTutorial_ChangeHudABTest,float,-1,,\nEnableFFAntihackInfoExtra,EnableFFAntihackInfoExtra,bool,False,,\nEnableTrustItemCountFromServer,EnableTrustItemCountFromServer,bool,False,,\nEnableNativeCheck,EnableNativeCheck,bool,False,,\nEnablePlatformCheck,EnablePlatformCheck,bool,False,,\nEnableMMKPlatformCheck,EnableMMKPlatformCheck,bool,False,,\nEnableSupCheck,EnableSupCheck,bool,False,,\nEnableCheckFileStates,EnableCheckFileStates,bool,False,,\nOptionalDeepFileCheck,OptionalDeepFileCheck,bool,False,,\nOptionalDownloadHashCheckOpen,OptionalDownloadHashCheckOpen,bool,False,,\nMemoryCheckString,MemoryCheckString,string,,,\nAgeCtrlAndroidBanCheckByInstallID,AgeCtrlAndroidBanCheckByInstallID,bool,False,,\nReturnToLobbyCheckAlbumOverTimeFile,ReturnToLobbyCheckAlbumOverTimeFile,bool,False,,\nEnableCheckOverlapWithSantioDummy,EnableCheckOverlapWithSantioDummy,bool,False,,\nEnableIngameQuickReport,EnableIngameQuickReport,bool,False,,\nAgeCtrl_iOSPrecheckForMinor,AgeCtrl_iOSPrecheckForMinor,bool,False,,\nAgeCtrl_CheckForThirdPartyBuild,AgeCtrl_CheckForThirdPartyBuild,bool,False,,\nAgeCtrl_PromptWhenBannedByStrategy_iOS,AgeCtrl_PromptWhenBannedByStrategy_iOS,bool,False,,\nAgeCtrl_PromptWhenBannedByStrategy_Android,AgeCtrl_PromptWhenBannedByStrategy_Android,bool,False,,\nBanStateDisabledArea,BanStateDisabledArea,string,US,CN,TW,TH,VN,ID,PT,ES,RU,KR,FR,DE,TR,IN,JP,RO,SA,MM,PK,BD,MY,,\nEnableCheckMatchEndDelayWhenDisconnect,EnableCheckMatchEndDelayWhenDisconnect,bool,False,,\nChatReportMaxTimes,ChatReportMaxTimes,uint32,0,,\nClanReportMaxTimes,ClanReportMaxTimes,uint32,0,,\nBlocklistMaxNum,BlocklistMaxNum,Int32,0,,",
    "latest_release_version": "OB54",
    "use_multithread_hash": true,
    "should_check_ab_load": false,
    "should_check_ab_exist": true,
    "use_regional_gamevar": true,
    "enable_hash_pdcache": true,
    "device_whitelist_priority": 0,
    "quality_level": 0,
    "graphic_level": 0,
    "show_high_framerate_UI": false,
    "high_frame_default": 0,
    "resolution_reduceRate_blit_type": null,
    "device_whitelist_sp_priority": 0,
    "apply_skin": 0,
    "enable_reduce_rate": false,
    "enable_min_resolution_height": false,
    "enable_min_height": false,
    "enable_unmap_web_view_vm": false,
    "device_whitelist_version": "",
    "device_whitelist_sp_version": "",
    "whitelist_mask": 0,
    "whitelist_info": "",
    "whitelist_sp_mask": 0,
    "whitelist_sp_info": "",
    "force_refresh_restype": "optionalavatarres",
    "should_check_ab_size": true,
    "ggp_url": "gin.freefiremobile.com",
    "abhotupdate_check": "cache_res;assetindexer;SH-Gpp",
    "hotfile_force_update": true,
    "multi_region": ""
}